print('Preencha os campos com as informações sobre sua data de nascimento (apenas números).')
dia=input('Dia: ')
mes=input('Mês: ')
ano=input('Ano: ')
print('Sua data de nascimento é', dia, '/', mes, '/', ano)